language: ruby

cache:
  bundler: false
  directories:
    - vendor/assets/bower
    - vendor/bundle

rvm:
  - 2.2.3
  - 2.0.0

bundler_args: --jobs=3 --retry=3

before_script:
  - npm install -g bower
  - bower install

script:
  - bundle exec rubocop -S -E
  - bundle exec middleman build --verbose
